-- ============================================================================
-- 002_full_feature_tables.sql
-- Creates the 34 feature tables used by the OmniRank backend that are missing
-- from the Supabase instance. Column sets were derived from the actual REST
-- calls in backend/app (insert payloads, patch payloads, select/order/filter
-- params), cross-checked against the canonical per-feature schemas in
-- /supabase/migrations.
--
-- Safe to re-run: every statement uses IF NOT EXISTS.
-- Valid for the Supabase SQL editor (Postgres 15). gen_random_uuid() is
-- built in (pgcrypto is preinstalled on Supabase).
--
-- RLS: every table has row level security ENABLED with NO policies.
-- The backend talks to PostgREST with the service-role key, which bypasses
-- RLS; anon/authenticated keys are therefore locked out (deny by default).
--
-- External references: projects(id) must already exist (core schema).
-- keyword_mappings.keyword_id / keyword_gaps.keyword_id logically reference
-- keywords(id) (bigint), but no FK is declared here because the keywords
-- table is not part of this migration.
-- ============================================================================


-- ────────────────────────────────────────────────────────────────────────────
-- audit_schedules — app/services/audit_service.py, app/services/scheduler.py
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists audit_schedules (
  id          bigint generated by default as identity primary key,
  project_id  uuid not null references projects(id) on delete cascade,
  audit_type  text,                          -- full_site, crawl_errors, broken_links, schema_validation, performance, orphan_pages
  frequency   text default 'weekly',         -- daily, weekly, monthly
  enabled     boolean default true,
  last_run    timestamptz,
  next_run    timestamptz,
  config      jsonb default '{}'::jsonb,
  created_at  timestamptz default now(),
  unique (project_id, audit_type)            -- audit_service patches by project_id + audit_type
);
create index if not exists idx_audit_schedules_project_id on audit_schedules(project_id);
create index if not exists idx_audit_schedules_next_run   on audit_schedules(next_run);
alter table audit_schedules enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- audit_runs — app/services/audit_service.py, app/services/scheduler.py,
--              app/services/wins_service.py
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists audit_runs (
  id                  bigint generated by default as identity primary key,
  project_id          uuid not null references projects(id) on delete cascade,
  audit_type          text,
  status              text default 'pending', -- pending, running, completed, failed
  started_at          timestamptz,
  completed_at        timestamptz,
  total_pages_checked bigint default 0,
  issues_found        bigint default 0,
  critical_count      bigint default 0,
  warning_count       bigint default 0,
  summary             text,
  result              jsonb default '{}'::jsonb,
  created_at          timestamptz default now()
);
create index if not exists idx_audit_runs_project_id on audit_runs(project_id);
create index if not exists idx_audit_runs_status     on audit_runs(status);
create index if not exists idx_audit_runs_created    on audit_runs(created_at desc);
alter table audit_runs enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- audit_issues — app/services/audit_service.py, app/services/scheduler.py,
--                app/services/wins_service.py
-- The scheduler's insert-then-patch dedupe relies on the unique constraint.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists audit_issues (
  id               bigint generated by default as identity primary key,
  project_id       uuid not null references projects(id) on delete cascade,
  audit_run_id     bigint references audit_runs(id) on delete cascade,
  issue_type       text,
  severity         text,                     -- critical, warning, info
  affected_url     text,
  affected_element text,
  description      text,
  recommendation   text,
  evidence         jsonb default '{}'::jsonb,
  status           text default 'open',      -- open, in_progress, resolved, ignored
  first_detected   timestamptz,
  last_detected    timestamptz,
  resolved_at      timestamptz,
  created_at       timestamptz default now(),
  unique (project_id, issue_type, affected_url)
);
create index if not exists idx_audit_issues_project_id on audit_issues(project_id);
create index if not exists idx_audit_issues_status     on audit_issues(status);
create index if not exists idx_audit_issues_severity   on audit_issues(severity);
create index if not exists idx_audit_issues_detected   on audit_issues(last_detected desc);
alter table audit_issues enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- audit_leads — app/main.py (public free-audit lead-gen funnel)
-- id is supplied by the app (uuid4 string), so the default is a fallback.
-- No project_id: leads are captured before signup.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists audit_leads (
  id         uuid primary key default gen_random_uuid(),
  email      text not null,
  domain     text not null,
  status     text default 'queued',          -- queued, crawling, completed, failed
  score      bigint,
  report     jsonb,
  created_at timestamptz default now()
);
create index if not exists idx_audit_leads_email   on audit_leads(email);
create index if not exists idx_audit_leads_created on audit_leads(created_at desc);
alter table audit_leads enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- bulk_content_jobs — app/services/bulk_content_service.py
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists bulk_content_jobs (
  id                 bigint generated by default as identity primary key,
  project_id         uuid not null references projects(id) on delete cascade,
  job_id             text not null unique,   -- "bulk_" + hex; app-level key
  status             text default 'queued',  -- queued, running, completed, failed, cancelled
  total_articles     bigint default 0,
  completed_articles bigint default 0,
  failed_articles    bigint default 0,
  template_name      text,
  enhance_with_ai    boolean default true,
  export_format      text default 'json',    -- json, csv, markdown
  schedule_publish   timestamptz,
  export_data        text,                   -- serialized export payload
  export_url         text,
  error_message      text,
  created_at         timestamptz default now()
);
create index if not exists idx_bulk_jobs_project_id on bulk_content_jobs(project_id);
alter table bulk_content_jobs enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- bulk_content_articles — app/services/bulk_content_service.py,
--                         app/services/wins_service.py
-- project_id is nullable: the service inserts articles keyed only by job_id,
-- but wins_service filters this table by project_id.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists bulk_content_articles (
  id                   bigint generated by default as identity primary key,
  project_id           uuid references projects(id) on delete cascade,
  job_id               text not null references bulk_content_jobs(job_id) on delete cascade,
  slug                 text,
  title                text,
  meta_description     text,
  h1                   text,
  body                 text,
  word_count           bigint default 0,
  reading_time_minutes bigint default 0,
  variables_used       jsonb default '{}'::jsonb,
  ai_enhanced          boolean default false,
  created_at           timestamptz default now()
);
create index if not exists idx_bulk_articles_project_id on bulk_content_articles(project_id);
create index if not exists idx_bulk_articles_job_id     on bulk_content_articles(job_id);
create index if not exists idx_bulk_articles_created    on bulk_content_articles(created_at desc);
alter table bulk_content_articles enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- cms_credentials — app/main.py, app/services/content_calendar_service.py,
--                   app/services/schema_injection_service.py
-- api_key / api_secret are encrypted by the app (secrets_crypto) before
-- storage: plain text columns. One row per project + platform.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists cms_credentials (
  id           uuid primary key default gen_random_uuid(),
  project_id   uuid not null references projects(id) on delete cascade,
  cms_platform text not null,                -- wordpress, shopify, webflow, custom
  endpoint_url text,
  api_key      text,                         -- encrypted app-side
  api_secret   text,                         -- encrypted app-side
  created_at   timestamptz default now(),
  unique (project_id, cms_platform)
);
create index if not exists idx_cms_credentials_project_id on cms_credentials(project_id);
alter table cms_credentials enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- competitors — app/services/competitor_service.py
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists competitors (
  id            bigint generated by default as identity primary key,
  project_id    uuid not null references projects(id) on delete cascade,
  domain        text not null,
  name          text,
  tld           text,
  country_code  text,
  language_code text,
  added_at      timestamptz default now(),   -- list is ordered by added_at desc
  last_analyzed timestamptz,
  created_at    timestamptz default now(),
  unique (project_id, domain)
);
create index if not exists idx_competitors_project_id on competitors(project_id);
alter table competitors enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- competitor_analysis — app/services/competitor_service.py,
--                       app/services/wins_service.py
-- top_keywords / top_pages / full_analysis are written as json.dumps strings
-- and json.loads'd on read; jsonb stores them as json string scalars, which
-- round-trips correctly through PostgREST.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists competitor_analysis (
  id                 bigint generated by default as identity primary key,
  competitor_id      bigint not null references competitors(id) on delete cascade,
  project_id         uuid not null references projects(id) on delete cascade,
  analysis_type      text,                   -- seo_overview, ...
  keyword_count      bigint default 0,
  top_keywords       jsonb,
  content_count      bigint default 0,
  avg_content_length numeric default 0,
  backlink_count     bigint default 0,
  referring_domains  bigint default 0,
  top_pages          jsonb,
  ai_insights        text,
  full_analysis      jsonb,
  analyzed_at        timestamptz default now(),  -- ordered by analyzed_at desc
  created_at         timestamptz default now()
);
create index if not exists idx_competitor_analysis_project_id    on competitor_analysis(project_id);
create index if not exists idx_competitor_analysis_competitor_id on competitor_analysis(competitor_id);
alter table competitor_analysis enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- outrank_strategies — app/services/competitor_service.py,
--                      app/services/wins_service.py
-- implementation_steps / content_gap are json.dumps strings (see note above).
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists outrank_strategies (
  id                   bigint generated by default as identity primary key,
  project_id           uuid not null references projects(id) on delete cascade,
  competitor_id        bigint not null references competitors(id) on delete cascade,
  strategy_type        text default 'content',
  target_keyword       text,
  competitor_position  bigint,
  recommended_action   text,
  implementation_steps jsonb,
  content_gap          jsonb,
  estimated_roi        text,
  priority             bigint default 0,     -- ordered by priority desc
  status               text default 'pending', -- pending, in_progress, completed
  created_at           timestamptz default now(),
  updated_at           timestamptz default now()
);
create index if not exists idx_outrank_strategies_project_id    on outrank_strategies(project_id);
create index if not exists idx_outrank_strategies_competitor_id on outrank_strategies(competitor_id);
create index if not exists idx_outrank_strategies_priority      on outrank_strategies(priority desc);
alter table outrank_strategies enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- content_calendar — app/services/content_calendar_service.py
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists content_calendar (
  id                 bigint generated by default as identity primary key,
  project_id         uuid not null references projects(id) on delete cascade,
  title              text not null,
  slug               text,
  body               text,
  meta_description   text,
  scheduled_date     timestamptz,            -- range-filtered and ordered asc
  status             text default 'scheduled', -- scheduled, draft, published, failed, cancelled
  cms_platform       text,
  auto_publish       boolean default true,
  auto_social_share  boolean default false,
  social_platforms   jsonb default '[]'::jsonb,
  featured_image_url text,
  content_type       text default 'article',
  cms_post_id        text,                   -- external id returned by the CMS
  cms_url            text,
  published_at       timestamptz,
  created_at         timestamptz default now()
);
create index if not exists idx_content_calendar_project_id on content_calendar(project_id);
create index if not exists idx_content_calendar_scheduled  on content_calendar(scheduled_date);
create index if not exists idx_content_calendar_status     on content_calendar(status);
alter table content_calendar enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- publishing_logs — app/services/content_calendar_service.py,
--                   app/services/wins_service.py
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists publishing_logs (
  id            bigint generated by default as identity primary key,
  project_id    uuid not null references projects(id) on delete cascade,
  calendar_id   bigint references content_calendar(id) on delete cascade,
  event_type    text,                        -- started, success, failed
  cms_platform  text,
  http_status   bigint,
  response_data jsonb default '{}'::jsonb,
  error_message text,
  created_at    timestamptz default now()
);
create index if not exists idx_publishing_logs_project_id  on publishing_logs(project_id);
create index if not exists idx_publishing_logs_calendar_id on publishing_logs(calendar_id);
alter table publishing_logs enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- edge_sites — app/services/edge_service.py, app/main.py
-- Looked up by site_token on every public snippet pageview.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists edge_sites (
  id           uuid primary key default gen_random_uuid(),
  project_id   uuid not null references projects(id) on delete cascade,
  domain       text not null,
  site_token   text not null unique,         -- "or_" + token_urlsafe, embedded in the snippet
  enabled      boolean default true,
  verified     boolean default false,
  verified_at  timestamptz,
  last_seen_at timestamptz,                  -- throttled heartbeat from the snippet
  created_at   timestamptz default now(),
  unique (project_id, domain)
);
create index if not exists idx_edge_sites_project_id on edge_sites(project_id);
alter table edge_sites enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- edge_rules — app/services/edge_service.py
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists edge_rules (
  id          bigint generated by default as identity primary key,
  project_id  uuid not null references projects(id) on delete cascade,
  site_id     uuid not null references edge_sites(id) on delete cascade,
  url_pattern text not null default '*',
  match_type  text default 'exact',          -- exact, prefix, contains, all
  rule_type   text not null,                 -- schema, title, meta_description, canonical, hreflang, meta
  payload     jsonb not null default '{}'::jsonb,
  enabled     boolean default true,
  priority    bigint default 5,              -- resolution ordered by priority desc
  source      text default 'manual',
  notes       text,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);
create index if not exists idx_edge_rules_project_id on edge_rules(project_id);
create index if not exists idx_edge_rules_site_id    on edge_rules(site_id);
create index if not exists idx_edge_rules_enabled    on edge_rules(enabled);
alter table edge_rules enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- product_feeds — app/services/feed_service.py
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists product_feeds (
  id              bigint generated by default as identity primary key,
  project_id      uuid not null references projects(id) on delete cascade,
  name            text,
  source_type     text default 'csv',        -- csv, url
  source_url      text,
  product_count   bigint default 0,
  issue_count     bigint default 0,
  optimized_count bigint default 0,
  truncated       boolean default false,
  status          text default 'ready',      -- importing, ready, failed
  last_imported   timestamptz,
  created_at      timestamptz default now()
);
create index if not exists idx_product_feeds_project_id on product_feeds(project_id);
alter table product_feeds enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- feed_products — app/services/feed_service.py
-- Bulk-inserted in chunks of 500; ordered by issue_count desc; filtered by
-- optimization_status (must default to 'pending' for the optimizer loop).
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists feed_products (
  id                    bigint generated by default as identity primary key,
  feed_id               bigint not null references product_feeds(id) on delete cascade,
  project_id            uuid not null references projects(id) on delete cascade,
  product_key           text not null,       -- feed's product id / SKU
  title                 text,
  description           text,
  brand                 text,
  category              text,
  price                 text,                -- kept verbatim from the feed (e.g. "12.99 USD")
  link                  text,
  availability          text,
  issues                jsonb default '[]'::jsonb,
  issue_count           bigint default 0,
  optimized_title       text,
  optimized_description text,
  optimization_status   text default 'pending', -- pending, optimized
  created_at            timestamptz default now()
);
create index if not exists idx_feed_products_feed_id     on feed_products(feed_id);
create index if not exists idx_feed_products_project_id  on feed_products(project_id);
create index if not exists idx_feed_products_issue_count on feed_products(issue_count desc);
create index if not exists idx_feed_products_opt_status  on feed_products(optimization_status);
alter table feed_products enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- git_connections — app/services/git_writeback_service.py
-- access_token is a GitHub PAT encrypted by the app before storage (text).
-- RLS with no policies keeps tokens unreadable by anon/authenticated keys.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists git_connections (
  id           uuid primary key default gen_random_uuid(),
  project_id   uuid not null references projects(id) on delete cascade,
  provider     text default 'github',
  repo_owner   text not null,
  repo_name    text not null,
  base_branch  text default 'main',
  access_token text not null,                -- encrypted app-side
  enabled      boolean default true,
  verified     boolean default false,
  verified_at  timestamptz,
  created_at   timestamptz default now(),
  unique (project_id, repo_owner, repo_name)
);
create index if not exists idx_git_connections_project_id on git_connections(project_id);
alter table git_connections enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- git_pull_requests — app/services/git_writeback_service.py
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists git_pull_requests (
  id            bigint generated by default as identity primary key,
  project_id    uuid not null references projects(id) on delete cascade,
  connection_id uuid not null references git_connections(id) on delete cascade,
  pr_number     bigint,
  pr_url        text,
  branch_name   text,
  title         text,
  description   text,
  fix_type      text,                        -- content, schema, meta, redirects, hreflang, other
  files         jsonb default '[]'::jsonb,   -- [{path, action}]
  status        text default 'open',         -- open, merged, closed
  created_at    timestamptz default now()
);
create index if not exists idx_git_prs_project_id on git_pull_requests(project_id);
create index if not exists idx_git_prs_status     on git_pull_requests(status);
alter table git_pull_requests enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- languages — app/services/multilingual_service.py
-- Integer id: language_id is typed int throughout the API.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists languages (
  id            bigint generated by default as identity primary key,
  project_id    uuid not null references projects(id) on delete cascade,
  language_code text not null,               -- en, es, fr, ...
  region_code   text,                        -- US, ES, ... (optional)
  display_name  text,
  is_default    boolean default false,
  is_enabled    boolean default true,
  created_at    timestamptz default now(),
  unique (project_id, language_code, region_code)
);
create index if not exists idx_languages_project_id on languages(project_id);
alter table languages enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- localized_content — app/services/multilingual_service.py,
--                     app/services/wins_service.py
-- Upserted by (project_id, language_id, source_url).
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists localized_content (
  id                 bigint generated by default as identity primary key,
  project_id         uuid not null references projects(id) on delete cascade,
  language_id        bigint not null references languages(id) on delete cascade,
  source_url         text,
  localized_url      text,
  title              text,
  description        text,
  content_markdown   text,
  keywords           jsonb default '[]'::jsonb,
  translation_status text default 'pending', -- pending, completed, needs_review
  translation_model  text,
  needs_human_review boolean default false,
  translated_by      text,
  created_at         timestamptz default now(),
  unique (project_id, language_id, source_url)
);
create index if not exists idx_localized_content_project_id  on localized_content(project_id);
create index if not exists idx_localized_content_language_id on localized_content(language_id);
alter table localized_content enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- hreflang_config — app/services/multilingual_service.py
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists hreflang_config (
  id                 bigint generated by default as identity primary key,
  project_id         uuid not null references projects(id) on delete cascade,
  source_url         text not null,
  target_url         text not null,
  target_language_id bigint not null references languages(id) on delete cascade,
  relationship_type  text default 'translation',
  is_configured      boolean default false,
  config_method      text default 'tag',     -- header, tag, sitemap
  created_at         timestamptz default now(),
  unique (project_id, source_url, target_language_id)
);
create index if not exists idx_hreflang_config_project_id on hreflang_config(project_id);
alter table hreflang_config enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- region_targeting — app/services/multilingual_service.py
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists region_targeting (
  id                   bigint generated by default as identity primary key,
  project_id           uuid not null references projects(id) on delete cascade,
  language_id          bigint not null references languages(id) on delete cascade,
  region_code          text not null,
  region_name          text,
  target_keywords      jsonb default '[]'::jsonb,
  local_content_needed boolean default false,
  seo_priority         bigint default 5,     -- ordered by seo_priority desc
  created_at           timestamptz default now(),
  unique (project_id, language_id, region_code)
);
create index if not exists idx_region_targeting_project_id on region_targeting(project_id);
alter table region_targeting enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- site_pages — app/services/internal_linking_service.py,
--              app/services/keyword_mapping_service.py
-- Upserted by (project_id, url).
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists site_pages (
  id         bigint generated by default as identity primary key,
  project_id uuid not null references projects(id) on delete cascade,
  url        text not null,
  title      text,
  content    text,                           -- first ~5K chars of page body
  topics     jsonb default '[]'::jsonb,
  word_count bigint default 0,
  created_at timestamptz default now(),
  unique (project_id, url)
);
create index if not exists idx_site_pages_project_id on site_pages(project_id);
alter table site_pages enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- internal_link_opportunities — app/services/internal_linking_service.py,
--                               app/services/wins_service.py
-- No unique(source,target): find_opportunities may legitimately re-store.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists internal_link_opportunities (
  id              bigint generated by default as identity primary key,
  project_id      uuid not null references projects(id) on delete cascade,
  source_page_id  bigint not null references site_pages(id) on delete cascade,
  target_page_id  bigint not null references site_pages(id) on delete cascade,
  anchor_text     text,
  relevance_score numeric,                   -- 0-1
  keyword_match   text,
  linking_reason  text,
  opportunity_type text,                     -- keyword_relevant, semantic, topic_cluster, orphan_rescue
  priority        bigint default 5,          -- ordered by priority desc
  status          text default 'pending',    -- pending, approved, implemented, rejected
  created_at      timestamptz default now()
);
create index if not exists idx_ilo_project_id on internal_link_opportunities(project_id);
create index if not exists idx_ilo_source     on internal_link_opportunities(source_page_id);
create index if not exists idx_ilo_status     on internal_link_opportunities(status);
alter table internal_link_opportunities enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- internal_links — app/services/internal_linking_service.py
-- Currently read-only in code (identify_orphans reads source_url/target_url);
-- writes are a TODO in implement_link(). Kept minimal to match actual usage.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists internal_links (
  id          bigint generated by default as identity primary key,
  project_id  uuid not null references projects(id) on delete cascade,
  source_url  text,
  target_url  text,
  created_at  timestamptz default now()
);
create index if not exists idx_internal_links_project_id on internal_links(project_id);
alter table internal_links enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- keyword_clusters — app/services/keyword_mapping_service.py
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists keyword_clusters (
  id           bigint generated by default as identity primary key,
  project_id   uuid not null references projects(id) on delete cascade,
  cluster_name text,
  seed_keyword text,
  keywords     jsonb default '[]'::jsonb,    -- array of keyword strings
  intent       text,                         -- informational, navigational, commercial, transactional
  volume       bigint default 0,             -- ordered by volume desc
  difficulty   numeric default 0,            -- average difficulty (may be fractional)
  created_at   timestamptz default now()
);
create index if not exists idx_keyword_clusters_project_id on keyword_clusters(project_id);
create index if not exists idx_keyword_clusters_volume     on keyword_clusters(volume desc);
alter table keyword_clusters enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- keyword_mappings — app/services/keyword_mapping_service.py,
--                    app/services/wins_service.py
-- keyword_id references the pre-existing keywords table (bigint id); the FK
-- is intentionally omitted because keywords is not created in this file.
-- Code relies on unique (project_id, keyword_id, url) to skip duplicates.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists keyword_mappings (
  id             bigint generated by default as identity primary key,
  project_id     uuid not null references projects(id) on delete cascade,
  keyword_id     bigint not null,            -- -> keywords(id)
  url            text,
  recommendation text,                       -- target, optimize
  priority       bigint default 5,           -- ordered by priority desc
  status         text default 'pending',
  created_at     timestamptz default now(),
  unique (project_id, keyword_id, url)
);
create index if not exists idx_keyword_mappings_project_id on keyword_mappings(project_id);
alter table keyword_mappings enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- keyword_gaps — app/services/keyword_mapping_service.py, app/main.py
-- keyword_id references the pre-existing keywords table (no FK, see above).
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists keyword_gaps (
  id             bigint generated by default as identity primary key,
  project_id     uuid not null references projects(id) on delete cascade,
  keyword_id     bigint not null,            -- -> keywords(id)
  gap_type       text,                       -- new_content_needed, no_url_assigned, ...
  volume         bigint default 0,
  difficulty     bigint default 0,
  recommendation text,
  priority       bigint default 5,           -- ordered by priority desc
  created_at     timestamptz default now()
);
create index if not exists idx_keyword_gaps_project_id on keyword_gaps(project_id);
create index if not exists idx_keyword_gaps_gap_type   on keyword_gaps(gap_type);
alter table keyword_gaps enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- oauth_tokens — app/api/analytics.py (GA4 / GSC Google OAuth)
-- access_token / refresh_token are encrypted by the app before storage.
-- One row per project + service, patched in place on refresh.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists oauth_tokens (
  id            bigint generated by default as identity primary key,
  project_id    uuid not null references projects(id) on delete cascade,
  service       text not null,               -- ga4, gsc
  access_token  text not null,               -- encrypted app-side
  refresh_token text,                        -- encrypted app-side
  expires_at    timestamptz,
  email         text,
  created_at    timestamptz default now(),
  unique (project_id, service)
);
create index if not exists idx_oauth_tokens_project_id on oauth_tokens(project_id);
alter table oauth_tokens enable row level security;

-- (plan_status intentionally NOT created as a table: in the codebase it is a
--  COLUMN on organizations, which already exists in this database.)

-- ────────────────────────────────────────────────────────────────────────────
-- schema_injection_jobs — app/services/schema_injection_service.py
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists schema_injection_jobs (
  id              uuid primary key default gen_random_uuid(),
  project_id      uuid not null references projects(id) on delete cascade,
  job_id          text not null unique,      -- "inj_" + hex; app-level key
  status          text not null default 'queued', -- queued, running, completed, failed
  total_urls      bigint default 0,
  processed_count bigint default 0,
  success_count   bigint default 0,
  failure_count   bigint default 0,
  schema_types    jsonb default '[]'::jsonb,
  cms_auto_detect boolean default true,
  error_message   text,
  created_at      timestamptz default now()
);
create index if not exists idx_schema_injection_jobs_project_id on schema_injection_jobs(project_id);
alter table schema_injection_jobs enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- schema_injections — app/services/schema_injection_service.py
-- request_body is the generated JSON-LD dict; response_body the CMS response.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists schema_injections (
  id            uuid primary key default gen_random_uuid(),
  project_id    uuid not null references projects(id) on delete cascade,
  batch_id      uuid,
  url           text not null,
  cms_platform  text,
  schema_type   text,
  status        text default 'pending',      -- pending, injected, failed
  error_message text,
  request_body  jsonb,
  response_body jsonb,
  created_at    timestamptz default now()
);
create index if not exists idx_schema_injections_project_id on schema_injections(project_id);
create index if not exists idx_schema_injections_batch_id   on schema_injections(batch_id);
alter table schema_injections enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- webhook_events — app/main.py (billing webhook replay protection)
-- The unique constraint IS the idempotency mechanism: the handler inserts
-- (provider, event_id) and treats a unique violation as a replay.
-- No project_id (provider-level events).
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists webhook_events (
  id         bigint generated by default as identity primary key,
  provider   text not null,                  -- razorpay, stripe
  event_id   text not null,
  created_at timestamptz default now(),
  unique (provider, event_id)
);
alter table webhook_events enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- wins_reports — app/services/wins_service.py, app/services/scheduler.py
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists wins_reports (
  id           bigint generated by default as identity primary key,
  project_id   uuid not null references projects(id) on delete cascade,
  period_start timestamptz,
  period_end   timestamptz,
  stats        jsonb default '{}'::jsonb,
  value_inr    bigint default 0,
  value_usd    bigint default 0,
  sent_to      text,
  sent_at      timestamptz,
  created_at   timestamptz default now()    -- weekly dedupe orders by created_at desc
);
create index if not exists idx_wins_reports_project_id on wins_reports(project_id);
create index if not exists idx_wins_reports_created    on wins_reports(created_at desc);
alter table wins_reports enable row level security;

-- ============================================================================
-- End of 002_full_feature_tables.sql (34 tables)
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- issue_resolutions — app/services/audit_service.py (resolve_issue)
-- (from canonical supabase/migrations/0012_technical_audits.sql)
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists issue_resolutions (
  id                  bigserial primary key,
  project_id          uuid not null references projects(id) on delete cascade,
  issue_id            bigint not null references audit_issues(id) on delete cascade,
  resolution_type     varchar(50),            -- auto_fix, manual_fix, ignored, false_positive
  resolution_details  text,
  resolved_by         varchar(255),
  verification_status varchar(50) default 'pending',
  verified_at         timestamptz,
  created_at          timestamptz default now()
);
create index if not exists idx_issue_resolutions_project_id on issue_resolutions(project_id);
create index if not exists idx_issue_resolutions_issue_id on issue_resolutions(issue_id);
alter table issue_resolutions enable row level security;

-- ────────────────────────────────────────────────────────────────────────────
-- url_assignments — app/services/keyword_mapping_service.py
-- (from canonical supabase/migrations/0010_keyword_mapping.sql)
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists url_assignments (
  id                 bigserial primary key,
  project_id         uuid not null references projects(id) on delete cascade,
  url                varchar(500) not null,
  title              varchar(500),
  assigned_keywords  jsonb,
  primary_keyword    varchar(255),
  secondary_keywords jsonb,
  target_volume      int,
  optimization_score int,
  content_gaps       jsonb,
  recommendations    text,
  last_optimized     timestamptz,
  created_at         timestamptz default now(),
  unique(project_id, url)
);
create index if not exists idx_url_assignments_project_id on url_assignments(project_id);
alter table url_assignments enable row level security;
