"""PDF report generator.

Generates white-label SEO reports using Claude for narrative
and converts HTML to PDF via headless browser or weasyprint.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

from app.clients.claude_client import AIUsageAccumulator, ClaudeClient
from app.services.branding import BrandingConfig

logger = logging.getLogger("omnirank.reports")


class ReportGenerator:
    """Generate SEO report HTML that can be converted to PDF."""

    def __init__(self, claude_client: ClaudeClient | None = None):
        self.claude = claude_client
        self.usage = AIUsageAccumulator()

    def generate_seo_report(
        self,
        project: dict[str, Any],
        keywords: list[dict],
        audit_data: dict | None = None,
        rank_data: list[dict] | None = None,
        competitor_data: list[dict] | None = None,
        white_label: bool = False,
        brand_name: str = "OMNI-RANK",
        branding: BrandingConfig | dict | None = None,
    ) -> dict[str, Any]:
        """Generate a full SEO report. Returns dict with title, summary, and html keys."""

        # Gather metrics
        domain = project.get("domain", project.get("client_url", "Unknown"))
        total_keywords = len(keywords)
        ranked_keywords = len([k for k in (rank_data or []) if k.get("position")])
        top_10 = len([k for k in (rank_data or []) if k.get("position") and k["position"] <= 10])
        top_3 = len([k for k in (rank_data or []) if k.get("position") and k["position"] <= 3])

        perf_score = audit_data.get("scores", {}).get("performance") if audit_data else None
        seo_score = audit_data.get("scores", {}).get("seo") if audit_data else None

        # AI narrative
        narrative = self._generate_narrative(project, keywords, audit_data, rank_data)

        date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")

        # ── Resolve branding ──────────────────────────────────────────────
        if isinstance(branding, dict):
            branding = BrandingConfig.from_dict(branding)
        if branding is None:
            project_branding = (project.get("settings") or {}).get("branding")
            branding = BrandingConfig.from_dict(project_branding)
        use_branding = branding.enabled or white_label
        primary = branding.primary_color
        secondary = branding.secondary_color
        accent = branding.accent_color
        brand = branding.resolved_agency_name(
            fallback=project.get("name", brand_name) if white_label else brand_name,
        )
        logo_html = branding.logo_html(fallback_text=brand) if use_branding else ""
        cover_title = branding.resolved_cover_title(project.get("name", domain))
        footer_tagline = branding.resolved_footer(fallback_agency=brand) if use_branding else (
            f"Generated by {brand} AI SEO Platform"
        )

        html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
body {{ font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a2e; margin: 0; padding: 0; font-size: 14px; line-height: 1.6; }}
.page {{ max-width: 800px; margin: 0 auto; padding: 40px; }}
.header {{ display: flex; justify-content: space-between; align-items: center; border-bottom: 3px solid {primary}; padding-bottom: 20px; margin-bottom: 30px; }}
.logo {{ font-size: 24px; font-weight: 700; color: {primary}; }}
.logo-img {{ margin-bottom: 4px; }}
.date {{ color: #666; font-size: 12px; }}
h1 {{ font-size: 28px; margin: 0 0 8px; color: #1a1a2e; }}
h2 {{ font-size: 20px; color: {primary}; margin: 30px 0 15px; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; }}
h3 {{ font-size: 16px; color: #374151; margin: 20px 0 10px; }}
.subtitle {{ color: #666; font-size: 14px; margin-bottom: 30px; }}
.metrics {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 20px 0; }}
.metric {{ background: #f8f9fa; border-radius: 8px; padding: 16px; text-align: center; }}
.metric-value {{ font-size: 28px; font-weight: 700; }}
.metric-label {{ font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 0.05em; margin-top: 4px; }}
.green {{ color: {accent}; }}
.amber {{ color: {secondary}; }}
.red {{ color: #dc2626; }}
.blue {{ color: {primary}; }}
table {{ width: 100%; border-collapse: collapse; margin: 15px 0; font-size: 13px; }}
th {{ text-align: left; padding: 10px 12px; background: #f3f4f6; color: #374151; font-weight: 600; font-size: 11px; text-transform: uppercase; }}
td {{ padding: 10px 12px; border-bottom: 1px solid #e5e7eb; }}
.narrative {{ background: #f8f9fa; border-left: 4px solid {primary}; padding: 20px; border-radius: 0 8px 8px 0; margin: 20px 0; }}
.footer {{ text-align: center; color: #999; font-size: 11px; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; }}
.badge {{ display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }}
.badge-green {{ background: #d1fae5; color: #065f46; }}
.badge-amber {{ background: #fef3c7; color: #92400e; }}
.badge-red {{ background: #fee2e2; color: #991b1b; }}
.cover {{ text-align: center; padding: 80px 40px 40px; border-bottom: 3px solid {primary}; margin-bottom: 40px; }}
.cover-title {{ font-size: 34px; color: {primary}; margin: 24px 0 8px; }}
.cover-subtitle {{ font-size: 16px; color: #666; }}
</style>
</head>
<body>
<div class="page">"""

        if use_branding and (branding.logo_url or branding.cover_title or branding.cover_subtitle):
            html += f"""
<div class="cover">
    {logo_html}
    <div class="cover-title">{cover_title}</div>
    <div class="cover-subtitle">{branding.cover_subtitle or f"Prepared for {project.get('name', domain)}"}</div>
    <div style="margin-top:16px;color:#888;font-size:12px;">{date_str}</div>
</div>"""

        html += f"""
<div class="header">
    <div>
        {logo_html if logo_html else f'<div class="logo">{brand}</div>'}
        <div style="font-size:12px;color:#666;">SEO Performance Report</div>
    </div>
    <div class="date">{date_str}</div>
</div>

<h1>SEO Report: {domain}</h1>
<p class="subtitle">Project: {project.get('name', domain)} | Generated by AI analysis</p>

<div class="metrics">
    <div class="metric">
        <div class="metric-value blue">{total_keywords}</div>
        <div class="metric-label">Keywords Tracked</div>
    </div>
    <div class="metric">
        <div class="metric-value {'green' if top_10 > 0 else 'amber'}">{top_10}</div>
        <div class="metric-label">In Top 10</div>
    </div>
    <div class="metric">
        <div class="metric-value {'green' if top_3 > 0 else 'amber'}">{top_3}</div>
        <div class="metric-label">In Top 3</div>
    </div>
    <div class="metric">
        <div class="metric-value {'green' if perf_score and perf_score > 80 else 'amber' if perf_score and perf_score > 50 else 'red'}">{int(perf_score) if perf_score else '—'}</div>
        <div class="metric-label">Performance Score</div>
    </div>
</div>

<h2>Executive Summary</h2>
<div class="narrative">{narrative}</div>

<h2>Keyword Rankings</h2>
<table>
<thead><tr><th>Keyword</th><th>Position</th><th>Change</th><th>Intent</th></tr></thead>
<tbody>"""

        for kw in keywords[:20]:
            pos = kw.get("latest_position")
            prev = kw.get("previous_position")
            change = ""
            if pos and prev:
                diff = prev - pos
                if diff > 0:
                    change = f'<span class="green">+{diff}</span>'
                elif diff < 0:
                    change = f'<span class="red">{diff}</span>'
                else:
                    change = '<span style="color:#999">—</span>'

            pos_badge = ""
            if pos:
                cls = "badge-green" if pos <= 10 else "badge-amber" if pos <= 30 else "badge-red"
                pos_badge = f'<span class="badge {cls}">#{pos}</span>'
            else:
                pos_badge = '<span style="color:#999">Not ranked</span>'

            html += f"""<tr><td>{kw.get('keyword', '')}</td><td>{pos_badge}</td><td>{change or '—'}</td><td>{kw.get('intent', '—')}</td></tr>"""

        html += "</tbody></table>"

        if audit_data:
            scores = audit_data.get("scores", {})
            html += f"""
<h2>Technical Performance</h2>
<div class="metrics">
    <div class="metric"><div class="metric-value">{int(scores.get('performance', 0)) if scores.get('performance') else '—'}</div><div class="metric-label">Performance</div></div>
    <div class="metric"><div class="metric-value">{int(scores.get('seo', 0)) if scores.get('seo') else '—'}</div><div class="metric-label">SEO</div></div>
    <div class="metric"><div class="metric-value">{int(scores.get('accessibility', 0)) if scores.get('accessibility') else '—'}</div><div class="metric-label">Accessibility</div></div>
    <div class="metric"><div class="metric-value">{int(scores.get('best_practices', 0)) if scores.get('best_practices') else '—'}</div><div class="metric-label">Best Practices</div></div>
</div>"""

        html += f"""
<div class="footer">
    {footer_tagline} | {date_str}<br>
    This report is confidential and intended for the recipient only.
    {f'<br>{branding.website}' if use_branding and branding.website else ''}
    {f' · {branding.email}' if use_branding and branding.email else ''}
</div>
</div>
</body>
</html>"""

        domain = project.get("domain", project.get("client_url", "Unknown"))
        title = f"SEO Report — {project.get('name', domain)}"
        summary = narrative if isinstance(narrative, str) else str(narrative)

        return {"title": title, "summary": summary[:500], "html": html}

    def _generate_narrative(
        self,
        project: dict,
        keywords: list[dict],
        audit_data: dict | None,
        rank_data: list[dict] | None,
    ) -> str:
        """Use Claude to generate an executive summary."""
        if not self.claude:
            return (
                f"This report covers {len(keywords)} tracked keywords for {project.get('domain', 'your site')}. "
                f"Review the keyword rankings and technical scores below for detailed insights."
            )

        context = f"""Domain: {project.get('domain')}
Keywords tracked: {len(keywords)}
Rankings found: {len([k for k in (rank_data or []) if k.get('position')])}
Performance score: {audit_data.get('scores', {}).get('performance') if audit_data else 'N/A'}
SEO score: {audit_data.get('scores', {}).get('seo') if audit_data else 'N/A'}"""

        resp = self.claude.complete(
            messages=[{"role": "user", "content": f"Write a 3-4 sentence executive summary for this SEO report:\n{context}"}],
            system="You are a professional SEO consultant writing a client-facing report summary. Be concise, data-driven, and actionable.",
            max_tokens=300, temperature=0.3,
        )
        self.usage.record(resp)
        return resp.content
