import Link from "next/link";

export const metadata = { title: "Terms of Service — OMNI-RANK" };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <header className="border-b border-slate-200 bg-white">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center">
          <Link href="/" className="font-bold text-lg">OR OMNI-RANK</Link>
        </div>
      </header>
      <main className="max-w-3xl mx-auto px-6 py-16 prose prose-slate">
        <h1>Terms of Service</h1>
        <p className="text-sm text-slate-500">Last updated: July 2026</p>

        <p>
          These terms govern your use of OMNI-RANK (&quot;the Service&quot;), a product of{" "}
          <strong>Surrvik E-Mobility</strong> (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;).
          By creating an account or using the Service you agree to these terms. If you use the
          Service on behalf of a company, you confirm you are authorised to bind that company.
        </p>

        <h2>1. The Service</h2>
        <p>
          OMNI-RANK provides SEO and AI-search visibility software: keyword research, rank
          tracking, technical audits, content tooling, AI-visibility monitoring, social content
          tooling, and reporting. We continuously improve the Service and may add, change, or
          retire features; if we retire something material to a paid plan we will give reasonable
          notice.
        </p>

        <h2>2. Accounts and acceptable use</h2>
        <ul>
          <li>Only connect websites, analytics properties, and accounts you own or are authorised to manage.</li>
          <li>Keep your credentials confidential; you are responsible for activity under your account.</li>
          <li>Do not use the Service to send spam, infringe intellectual property, break any platform&apos;s terms, attempt to breach our security, or resell the Service without a written agreement.</li>
          <li>API keys and reports may be shared with your clients as part of white-label features, but access to the platform itself is per the seats and limits of your plan.</li>
        </ul>

        <h2>3. Plans, billing and cancellation</h2>
        <ul>
          <li>Paid plans are billed in advance, monthly or annually, via Stripe or Razorpay, and renew automatically until cancelled.</li>
          <li>You can cancel anytime from Billing settings; access continues until the end of the current paid period.</li>
          <li>Fees already paid are non-refundable except where required by law. Taxes (including GST where applicable) are added as required.</li>
          <li>We may change prices with at least 30 days&apos; notice; changes apply from your next renewal.</li>
          <li>Usage limits (analyses, tracked keywords, agent runs) are per your plan; we may throttle usage that exceeds them.</li>
        </ul>

        <h2>4. No ranking guarantees</h2>
        <p>
          Search engines and AI answer engines change constantly and are outside our control.
          Scores, projections, benchmarks, and illustrative scenarios shown in the product or on
          this site are informational and are <strong>not</strong> a promise of specific rankings,
          citations, traffic, or revenue. Content generated by AI features should be reviewed by
          you before publication — you are responsible for what you publish.
        </p>

        <h2>5. Your data and content</h2>
        <p>
          You retain all rights to the data and content you bring to the Service and to reports
          generated for you. You grant us the licence needed to process that data to operate the
          Service. Our handling of personal data is described in the{" "}
          <Link href="/privacy">Privacy Policy</Link>.
        </p>

        <h2>6. Intellectual property</h2>
        <p>
          The Service, its software, design, and branding are owned by Surrvik E-Mobility or its
          licensors. These terms grant you a limited, non-exclusive, non-transferable right to use
          the Service during your subscription; they do not transfer any ownership.
        </p>

        <h2>7. Disclaimer and limitation of liability</h2>
        <p>
          The Service is provided &quot;as is&quot; and &quot;as available&quot;, without
          warranties of any kind, express or implied. To the maximum extent permitted by law,
          Surrvik E-Mobility is not liable for indirect, incidental, special, or consequential
          damages, or loss of profits, revenue, or data; and our total aggregate liability for any
          claim relating to the Service is limited to the fees you paid us in the twelve months
          preceding the claim.
        </p>

        <h2>8. Suspension and termination</h2>
        <p>
          We may suspend or terminate accounts that materially breach these terms, abuse the
          platform, or create legal risk, with notice where practicable. You may delete your
          account at any time; sections that by their nature survive (billing obligations,
          liability limits, IP) survive termination.
        </p>

        <h2>9. Governing law</h2>
        <p>
          These terms are governed by the laws of India, and disputes are subject to the exclusive
          jurisdiction of the courts at the registered office of Surrvik E-Mobility.
        </p>

        <h2>10. Changes to these terms</h2>
        <p>
          We may update these terms; material changes will be notified by email or in-product
          notice at least 14 days before they take effect. Continued use after that date
          constitutes acceptance.
        </p>

        <h2>11. Contact</h2>
        <p>
          Surrvik E-Mobility<br />
          Email: <a href="mailto:legal@surrvik.com">legal@surrvik.com</a>
        </p>

        <p className="text-sm text-slate-500">
          See also our <Link href="/privacy">Privacy Policy</Link>.
        </p>
      </main>
    </div>
  );
}
